export const ADMIN_TOAST_HIDE_MS = 3000;
export const ADMIN_FEEDBACK_TOAST_HIDE_MS = 3200;
export const ADMIN_MODAL_CLOSE_MS = 1500;
export const ADMIN_ACCOUNT_SEARCH_DEBOUNCE_MS = 400;

export const DELIVERY_TOAST_HIDE_MS = 3500;
export const DELIVERY_ACTION_REFRESH_MS = 1800;
export const DELIVERY_TRANSFER_REFRESH_MS = 1500;
export const DELIVERY_SHORT_RETRY_MS = 500;
export const DELIVERY_PHOTO_DIALOG_DELAY_MS = 100;

export const WAREHOUSE_STAFF_REFRESH_MS = 1000;
export const WAREHOUSE_LOGIN_ID_LENGTH = 8;
export const WAREHOUSE_PASSWORD_LENGTH = 6;
